### ISSUE TITLE
dob_violations may not be updating automatically

### ISSUE THREAD

**Issue by sraby** [JustFixNYC/nycdb-k8s-loader#33]
Just looked at the dob_violations dataset and noticed that the most up to date record was issued on 12/07/2018. Is it possible that the dataset wasn't configured to update automatically?

**Comment by toolness** [comment]
Oh dang, good catch! I just looked at the [Slack channel/log]() and indeed `dob_violations` is nowhere on there... Looking at the part of the source that defines when things are scheduled, it's clear why--`dob_violations` is nowhere on here:

https://github.com/JustFixNYC/nycdb-k8s-loader/blob/7a7df8e18bca384578f0903ec31678e2c9e4fc65/aws_schedule_tasks.py#L66-L76

Want to issue a PR that adds it?  While I'd eventually like to have the above script be re-run automatically on every push to `master`, right now it doesn't, but I can show you how to do it so you can bust it up yourself, if you want.

**Comment by toolness** [comment]
Fixed by #34!
